# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lucky Lukes Maker-Stories
email: "l.wiseby@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Wanna now what I have been up to lately? Interested in software and tech stuff?
  Or maybe searching for answers by reading some of my solutions on problems i stombled over?
  This site is all about problemsolving and interesting projects I want to share with you.
  Come along and read some of my posts, follow one of my DIY guides or maybe read a good story or two.
  This is a peaceful and simple place to be.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  wiseby
linkedin_username: lucas-wiseby-52352216b
web_site: https://wisebydesign.se

# Defaults
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
